### ISSUE TITLE
Getting "URLCon is not a constructor" error

### ISSUE THREAD

**Issue by zrkrlc** [nicohman/reimagined-wildbow-scraper#1]
```
$ node app.js -t
X:\...\reimagined-wildbow-scraper-master\app.js:57
        var nexturl = new URLCon(next);
                      ^

TypeError: URLCon is not a constructor
    at IncomingMessage.<anonymous> (X:\...\reimagined-wildbow-scraper-mast
er\app.js:57:23)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

I fixed it by replacing const  `URLCon = require('url').URL;` with `const  URLCon = require('url');` and then replacing all instances of `var nexturl = new URLCon(next);` with `var nexturl = URLCon.parse(next);`.

**Comment by nicohman** [comment]
You're using a legacy version of node -- the url module changed between your version and the current one. I'll change the node version in the package.json, and see about adding in a way for it to detect which version you're using. Thanks for reporting this--never thought someone else would use this!

**Comment by nicohman** [comment]
Okay, pushed a commit that should detect your node version and adjust appropriately. Closing now, but please comment whether it works for your version or not. Worked for me, but want to double check. Thanks!
