### ISSUE TITLE
Errors when inputing any command relating to scraping

### ISSUE THREAD

**Issue by MGFlaccid** [nicohman/reimagined-wildbow-scraper#5]
For example, say I input "node app.js -a" to download Ward. This is what happens:

"C:\Users\rober\reimagined-wildbow-scraper>node app.js -a
Command Prompt - node  app.js -a[6668]: src\node_contextify.cc:628: Assertion `args[1]->IsString()' failed.
 1: node::DecodeWrite
 2: node::DecodeWrite
 3: uv_loop_fork
 4: v8::internal::interpreter::BytecodeDecoder::Decode
 5: v8::internal::RegExpImpl::Exec
 6: v8::internal::RegExpImpl::Exec
 7: v8::internal::RegExpImpl::Exec
 8: 000003E4B2284281
"

But if I input "node app.js -h" to check the help menu, it comes out fine:

"C:\Users\rober\reimagined-wildbow-scraper>node app.js -h

  Usage: app [options]

  Options:

    -V, --version         output the version number
    -r , --resume <json>  Resume from JSON file
    -a, --ward            Scrape Ward
    -w, --worm            Scrape Worm
    -t, --twig            Scrape Twig
    -p, --pact            Scrape Pact
    -g, --glow_worm       Scrape Worm 2 Prologue
    -h, --help            output usage information"

I have double and triple re-cloned the source, and made sure I had all npm dependencies the program seemed to need. I've tried both GitBash and Windows Command prompt (all run as administrator). But I have no idea in heck what is going on. Do you have any input?

**Comment by nicohman** [comment]
Okay, as far as I can that's a casualty of being on windows; One dependency, natives/graceful-fs v<4.0 , crashes with Node 10 or higher on windows. I've updated everything as much as possible, so could you try re-cloning and installing dependencies? Thanks.

**Comment by nicohman** [comment]
Closing due to lack of response.
